
export const WORDS = {
    AVOUT_ME: "Front-end development is my passion. I have enough knowledge of front-end JavaScript/React, web socket, Object oriented programming, and browser APIs. And a litle of Node/Express. :) __ I have a motivation to learn new things.",
    FIRST_NAME: 'Narek',
    LAST_NAME: 'Petrosyan',
    ABOUT: 'about',
    ME: 'me',
    AGE: 'age',
    MYAGE: '21',
    DATA_OF_BIRTH: '2000',
    MOUNTH_OF_BIRTH: '10',
    DAY_OF_BIRTH: '31',
    ADDRESS: 'address',
    MY_ADDRESS: 'Yerevan, Armenia',
    EMAIL_ADDRESS: 'narek.petrosyan.js@gmail.com',
    PHONE_NUMBER: '+(374) 98 738617',
    EMAIL: 'email',
    PHONE: 'phone',
    HOME: 'Home',
    RESUME: 'Resume',
    DOWNLOAD: 'download CV',
    TEXTDOWNLOADCV: 'Narek CV',
    CODING: 'Coding',
    SKILLS: 'Skills',
    EDUCATION:'Education',
    POSSITION: 'JavaScript Engineer',
    LINKDIN_URL: "https://www.linkedin.com/in/narek-petrosyan-a70452216/",
    GITHUB_URL: 'https://github.com/Narek-JS',
    ACHIEVEMENTS: 'Achievements'
}